# 系统环境
profile: dev

# 是否监控
monitor: true
# PprofAddrs 192.168.1.100:7272,10.0.0.1:7272
monitoraddrs: ['0.0.0.0:4272']

# PprofAddrs 192.168.1.100:7271,10.0.0.1:7271
pprofaddrs: ['0.0.0.0:4271']

# 服务监听地址
addr: 0.0.0.0:4080

# 日志配置文件
logger: config/logger.xml

# 数据库配置
db:
  #实例列表
  instances:
    master:
      driver: mysql
      url: root:@tcp(localhost:3306)/token_bank?timeout=12s&readTimeout=12s&writeTimeout=5s&parseTime=true&charset=utf8mb4

# 缓存配置
redis:
  #实例列表
  instances:
    master:
      url: 127.0.0.1:6379
      password: ""


appkeymap:
  s9QY7ZYad6Xm: 's98Y7ZYad6Xm'
  s3aY7ZYad6Xm: 'a24QY7ZYad6Xm'
  s1aY7ZYad6Xm: 'a1QY7ZYad6Xm'
  s5aY7ZYad6Xm: 'a4xQY7ZYad6Xm'
  newsadmin: '12ZUsa8Qdxwvg'
  newsoffice: '43eqybRm37NpJ'
  openaua: '232*dBg2&CUK*'